version: '3'
services:
  playground-web-db:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: playground-web
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
